In [1]:
# Python program to scrape resturant details from dineout.co.in webpage

# install library (bs4) and request
!pip install bs4
!pip install requests

Requirement already satisfied: bs4 in c:\users\vageesh\anaconda3\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\users\vageesh\anaconda3\lib\site-packages (from bs4) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\vageesh\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.2.1)
Requirement already satisfied: requests in c:\users\vageesh\anaconda3\lib\site-packages (2.26.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\vageesh\anaconda3\lib\site-packages (from requests) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\vageesh\anaconda3\lib\site-packages (from requests) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\vageesh\anaconda3\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\vageesh\anaconda3\lib\site-packages (from requests) (2.0.4)

In [2]:
# import BeautifulSoup
from bs4 import BeautifulSoup
import requests

# request Dineout webpage for data
page = requests.get('https://www.dineout.co.in/delhi-restaurants/buffet-special')
page

In [3]:
# extract data from Dineout webpage
src = BeautifulSoup(page.content)

In [4]:
# scrape data for name of the resturant
name = []
for i in src.find_all("a",class_="restnt-name ellipsis"):
    name.append(i.text.replace('\n',''))

# scrape data for cuisine
cuisine = []
for i in src.find_all("div",class_="detail-info"):
    cuisine.append(i.text.replace('\n',''))

# scrape data for resturant location    
location = []
for i in src.find_all("div",class_="restnt-loc ellipsis"):
    location.append(i.text.replace('\n',''))

# scrape data for resturant rating
rating = []
for i in src.find_all("div",class_="restnt-rating rating-4"):
    rating.append(i.text.replace('\n',''))

# scrape data for resturant image URL
img = []
for i in src.find_all("img",class_="no-img"):
    img.append(i['data-src'])

# display the data collected. Resturant name | cuisine | location | rating | image URL 
for val in range(0,len(name)):
    print(val+1,name[val],'|',cuisine[val],'|',location[val],'| Rating:',rating[val],'|',img[val],'|\n')

1 Castle Barbeque | ₹ 2,000 for 2 (approx) | North Indian, Chinese | Connaught Place, Central Delhi | Rating: 3.5 | https://im1.dineout.co.in/images/uploads/restaurant/sharpen/8/k/b/p86792-16062953735fbe1f4d3fb7e.jpg?tr=tr:n-medium |

2 Jungle Jamboree | ₹ 1,400 for 2 (approx) | North Indian, Asian, Italian | 3CS Mall,Lajpat Nagar - 3, South Delhi | Rating: 3.9 | https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/h/c/p3643-144497865356209fdd65746.jpg?tr=tr:n-medium |

3 Castle Barbeque | ₹ 2,000 for 2 (approx) | Chinese, North Indian | Pacific Mall,Tagore Garden, West Delhi | Rating: 3.9 | https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/j/o/p38113-15959192065f1fcb666130c.jpg?tr=tr:n-medium |

4 Cafe Knosh | ₹ 3,000 for 2 (approx) | Italian, Continental3 deals available | The Leela Ambience Convention Hotel,Shahdara, East Delhi | Rating: 4.3 | https://im1.dineout.co.in/images/uploads/restaurant/sharpen/4/p/m/p406-15438184745c04ccea491bc.jpg?tr=tr:n-medium |

5 The Barbeque Company | ₹ 1,700 for 2 (approx) | North Indian, Chinese4 deals available | Gardens Galleria,Sector 38A, Noida | Rating: 4 | https://im1.dineout.co.in/images/uploads/restaurant/sharpen/7/p/k/p79307-16051787755fad1597f2bf9.jpg?tr=tr:n-medium |

6 India Grill | ₹ 2,400 for 2 (approx) | North Indian, Italian | Hilton Garden Inn,Saket, South Delhi | Rating: 3.9 | https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/v/t/p2687-1482477169585cce712b90f.jpg?tr=tr:n-medium |

7 Delhi Barbeque | ₹ 1,800 for 2 (approx) | North Indian | Taurus Sarovar Portico,Mahipalpur, South Delhi | Rating: 3.7 | https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/v/f/p52501-16006856545f68865616659.jpg?tr=tr:n-medium |

8 The Monarch - Bar Be Que Village | ₹ 1,900 for 2 (approx) | North Indian | Indirapuram Habitat Centre,Indirapuram, Ghaziabad | Rating: 3.8 | https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/n/o/p34822-15599107305cfa594a13c24.jpg?tr=tr:n-medium |

9 World Cafe | ₹ 2,400 for 2 (approx) | North Indian, Italian | Vibe by The Lalit Traveller,Sector 35, Faridabad | Rating: 4.2 | https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/p/y/p12366-1466935020576fa6ecdc359.jpg?tr=tr:n-medium |

10 Indian Grill Room | ₹ 2,200 for 2 (approx) | North Indian, Mughlai1 deal available | Suncity Business Tower,Golf Course Road, Gurgaon | Rating: 4.3 | https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/y/f/p549-165000147262590640c0afc.jpg?tr=tr:n-medium |

11 Mad 4 Bar B Que | ₹ 800 for 2 (approx) | North Indian | Sector 29, Faridabad | Rating: 3.6 | https://im1.dineout.co.in/images/uploads/restaurant/sharpen/4/n/t/p43488-1647323111623027e763947.jpg?tr=tr:n-medium |

12 Barbeque 29 | ₹ 1,500 for 2 (approx) | North Indian, Mughlai, Desserts, Beverages | NIT, Faridabad | Rating: 4.2 | https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/w/r/p58842-15624171585d209806d9143.jpg?tr=tr:n-medium |

13 Glasshouse | ₹ 3,400 for 2 (approx) | European, Italian, Asian, Continental | DoubleTree By Hilton Gurugram Baani Square,Sector 50, Gurgaon | Rating: 4 | https://im1.dineout.co.in/images/uploads/restaurant/sharpen/9/m/a/p9875-1645177960620f6c68ecfef.jpg?tr=tr:n-medium |

In [5]:
# make a dataframe to store resturant information
import pandas as pd

db = pd.DataFrame({'Resturant Name':name,'Cuisine':cuisine,'Location':location,'Ratings':rating,'Image URL':img})
db.index +=1
db

,Resturant Name,Cuisine,Location,Ratings,Image URL
1,Castle Barbeque,"₹ 2,000 for 2 (approx) | North Indian, Chinese","Connaught Place, Central Delhi",3.5,https://im1.dineout.co.in/images/uploads/resta...
2,Jungle Jamboree,"₹ 1,400 for 2 (approx) | North Indian, Asian, ...","3CS Mall,Lajpat Nagar - 3, South Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
3,Castle Barbeque,"₹ 2,000 for 2 (approx) | Chinese, North Indian","Pacific Mall,Tagore Garden, West Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
4,Cafe Knosh,"₹ 3,000 for 2 (approx) | Italian, Continental3...","The Leela Ambience Convention Hotel,Shahdara, ...",4.3,https://im1.dineout.co.in/images/uploads/resta...
5,The Barbeque Company,"₹ 1,700 for 2 (approx) | North Indian, Chinese...","Gardens Galleria,Sector 38A, Noida",4,https://im1.dineout.co.in/images/uploads/resta...
6,India Grill,"₹ 2,400 for 2 (approx) | North Indian, Italian","Hilton Garden Inn,Saket, South Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
7,Delhi Barbeque,"₹ 1,800 for 2 (approx) | North Indian","Taurus Sarovar Portico,Mahipalpur, South Delhi",3.7,https://im1.dineout.co.in/images/uploads/resta...
8,The Monarch - Bar Be Que Village,"₹ 1,900 for 2 (approx) | North Indian","Indirapuram Habitat Centre,Indirapuram, Ghaziabad",3.8,https://im1.dineout.co.in/images/uploads/resta...
9,World Cafe,"₹ 2,400 for 2 (approx) | North Indian, Italian","Vibe by The Lalit Traveller,Sector 35, Faridabad",4.2,https://im1.dineout.co.in/images/uploads/resta...
10,Indian Grill Room,"₹ 2,200 for 2 (approx) | North Indian, Mughlai...","Suncity Business Tower,Golf Course Road, Gurgaon",4.3,https://im1.dineout.co.in/images/uploads/resta...
11,Mad 4 Bar B Que,₹ 800 for 2 (approx) | North Indian,"Sector 29, Faridabad",3.6,https://im1.dineout.co.in/images/uploads/resta...
12,Barbeque 29,"₹ 1,500 for 2 (approx) | North Indian, Mughlai...","NIT, Faridabad",4.2,https://im1.dineout.co.in/images/uploads/resta...
13,Glasshouse,"₹ 3,400 for 2 (approx) | European, Italian, As...","DoubleTree By Hilton Gurugram Baani Square,Sec...",4,https://im1.dineout.co.in/images/uploads/resta...